#!/usr/bin/env node
/**
 * Make `./gradlew assembleRelease` produce a *signed* APK.
 *
 * The Capacitor-generated android/ project is a local artifact (it is not
 * committed — the APK can only be built on a machine with an Android SDK), and
 * a stock `cap add android` produces an *unsigned* release APK that no phone
 * will install. This script wires signing up idempotently, with no hand-editing
 * of Gradle files and no secrets in the repo:
 *
 *   1. creates a release keystore with `keytool` if there isn't one yet
 *   2. stores its credentials in android/keystore.properties  (git-ignored)
 *   3. generates android/app/ana24-signing.gradle, which re-opens the
 *      `android {}` block to attach `signingConfigs.release`
 *   4. appends a single `apply from:` line to android/app/build.gradle
 *   5. stamps android/app/build.gradle with package.json's version, so the APK,
 *      the download manifest and the site all report the same version
 *
 * Safe to re-run: every step checks for existing work first.
 *
 * Overrides (optional):
 *   ANA24_KEYSTORE           path to an existing keystore to reuse
 *   ANA24_KEY_ALIAS          key alias                  (default: ana24)
 *   ANA24_KEYSTORE_PASSWORD  store/key password         (default: generated once)
 */
import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { relative, resolve, sep } from 'node:path'
import {
  ANDROID_DIR,
  APP_ID,
  BUILD_GRADLE,
  DEFAULT_KEYSTORE,
  KEYSTORE_PROPERTIES,
  SIGNING_GRADLE,
  readAppVersion,
  readKeystoreProperties,
  toVersionCode,
} from './lib/android-release.mjs'

const log = (message) => console.log(`[android-signing] ${message}`)
const fail = (message) => {
  console.error(`[android-signing] ${message}`)
  process.exit(1)
}

if (!existsSync(ANDROID_DIR)) {
  fail(
    `No ${ANDROID_DIR}/ project found. Generate it once with "npm run cap:add:android" ` +
      '(needs a web build and the Android SDK), then re-run this script.',
  )
}

const alias = process.env.ANA24_KEY_ALIAS || 'ana24'
const keystorePath = resolve(process.env.ANA24_KEYSTORE || DEFAULT_KEYSTORE)

/* --------------------------- 1. The keystore ------------------------------ */

const existing = readKeystoreProperties()
const password =
  process.env.ANA24_KEYSTORE_PASSWORD || existing.storePassword || randomBytes(24).toString('base64url')

if (existsSync(keystorePath)) {
  log(`Reusing the existing keystore at ${keystorePath}.`)
} else {
  log(`Creating a release keystore at ${keystorePath} …`)
  try {
    execFileSync(
      'keytool',
      [
        '-genkeypair',
        '-keystore',
        keystorePath,
        '-alias',
        alias,
        '-keyalg',
        'RSA',
        '-keysize',
        '2048',
        '-validity',
        '10000',
        '-storetype',
        'PKCS12',
        '-storepass',
        password,
        '-keypass',
        password,
        '-dname',
        `CN=ANA24, OU=${APP_ID}, O=ANA24, L=Global, ST=Global, C=US`,
      ],
      { stdio: ['ignore', 'ignore', 'pipe'] },
    )
    log('Keystore created.')
  } catch (error) {
    if (error?.code === 'ENOENT') {
      fail(
        'keytool was not found. It ships with the JDK that Gradle already needs — install JDK 17+ ' +
          '(Android Studio bundles one) and re-run.',
      )
    }
    fail(`keytool failed: ${error?.stderr?.toString()?.trim() || error?.message || 'unknown error'}`)
  }
}

/* ---------------------- 2. Credentials (git-ignored) ---------------------- */

// Gradle resolves storeFile against the android/ root project, so keep the path
// relative to it (with forward slashes, which Java accepts on every OS).
const storeFile = relative(resolve(ANDROID_DIR), keystorePath).split(sep).join('/')

writeFileSync(
  KEYSTORE_PROPERTIES,
  `# Generated by scripts/android-signing.mjs — DO NOT COMMIT.
# These credentials sign the ANA24 Android app (${APP_ID}).
# Losing this file, or the keystore it points at, means you can never ship an
# update under the same package name again. Back both up somewhere safe.
storeFile=${storeFile}
storePassword=${password}
keyAlias=${alias}
keyPassword=${password}
`,
  { mode: 0o600 },
)
log(`Wrote ${KEYSTORE_PROPERTIES} for alias "${alias}".`)

/* ------------------- 3. The applied Gradle signing file ------------------- */

const version = readAppVersion()
const versionCode = toVersionCode(version)

writeFileSync(
  SIGNING_GRADLE,
  `// GENERATED by scripts/android-signing.mjs — do not edit, do not commit.
// Re-opens the \`android {}\` block declared in app/build.gradle to attach the
// release signing config, reading the keystore details from the git-ignored
// keystore.properties at the android/ project root.

def ana24KeystoreProps = rootProject.file('keystore.properties')

if (!ana24KeystoreProps.exists()) {
    throw new GradleException('Missing android/keystore.properties — run: npm run apk:signing')
}

def ana24Props = new Properties()
ana24KeystoreProps.withInputStream { ana24Props.load(it) }

android {
    signingConfigs {
        ana24Release {
            storeFile rootProject.file(ana24Props['storeFile'])
            storePassword ana24Props['storePassword']
            keyAlias ana24Props['keyAlias']
            keyPassword ana24Props['keyPassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.ana24Release
        }
    }
}
`,
)
log(`Generated ${SIGNING_GRADLE}.`)

/* --------------------- 4. Wire it into build.gradle ----------------------- */

let buildGradle = readFileSync(BUILD_GRADLE, 'utf8')
const applyLine = "apply from: 'ana24-signing.gradle'"

if (buildGradle.includes(applyLine)) {
  log(`${BUILD_GRADLE} already applies the signing config.`)
} else {
  buildGradle = `${buildGradle.replace(/\s*$/, '')}

// ANA24 release signing (generated by scripts/android-signing.mjs)
${applyLine}
`
  log(`Attached the signing config to ${BUILD_GRADLE}.`)
}

/* ------------------------ 5. Stamp the version ---------------------------- */

const versionCodeBefore = buildGradle
const stamped = buildGradle
  .replace(/(\bversionName\s+)"[^"]*"/, `$1"${version}"`)
  .replace(/(\bversionCode\s+)\d+/, `$1${versionCode}`)

if (stamped === versionCodeBefore) {
  log(`WARNING: could not find versionName/versionCode in ${BUILD_GRADLE} — set them manually.`)
} else {
  log(`Stamped version ${version} (versionCode ${versionCode}) into ${BUILD_GRADLE}.`)
}

writeFileSync(BUILD_GRADLE, stamped)

/* ------------------------------- Summary --------------------------------- */

log('')
log(`Ready. The release APK will be signed with "${alias}" (version ${version}).`)
log('Next: npm run apk:publish   # build the signed APK and publish it to the site')
log('Back up the keystore and its credentials — without them you cannot update the app.')